GET http://localhost:2022/buyers

###

GET http://localhost:2022/buyers/61f1747f2c5604a2c29fce6f

###

POST  http://localhost:2022/buyers
Content-Type: application/json

{
    "name": "Shahid",
    "items": "Redgear Cosmo 7.1"
}

###

PATCH http://localhost:2022/buyers/61f1747f2c5604a2c29fce6f

{
    "name": "Shahid Parvez",
    "items": "Redgear Cosmo 7.1"
}

###

DELETE http://localhost:2022/buyers/61f1776c869715aa217afff9