GET http://localhost:2022/buyers

###

GET http://localhost:2022/buyers/61f1747f2c5604a2c29fce6f

###
 
POST  http://localhost:2022/buyers
Content-Type: application/json

{
    "name": "Mainak",
    "items": "Philips Trimmer"
}

###

PATCH http://localhost:2022/buyers/61f3819f2bf5a8ac4a5cc6de
Content-Type: application/json

{
    "name": "Shahid Parvez",
    "items": "Redgear Cosmo 7.1"
}

###

DELETE http://localhost:2022/buyers/61f391b42bf5a8ac4a5cc6e6
